/* eslint-disable import/no-cycle */
/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = 'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* SURVEY LIST APP */
export const SURVEY_LIST_GET_LIST = 'SURVEY_LIST_GET_LIST';
export const SURVEY_LIST_GET_LIST_SUCCESS = 'SURVEY_LIST_GET_LIST_SUCCESS';
export const SURVEY_LIST_GET_LIST_ERROR = 'SURVEY_LIST_GET_LIST_ERROR';
export const SURVEY_LIST_GET_LIST_WITH_FILTER = 'SURVEY_LIST_GET_LIST_WITH_FILTER';
export const SURVEY_LIST_GET_LIST_WITH_ORDER = 'SURVEY_LIST_GET_LIST_WITH_ORDER';
export const SURVEY_LIST_GET_LIST_SEARCH = 'SURVEY_LIST_GET_LIST_SEARCH';
export const SURVEY_LIST_ADD_ITEM = 'SURVEY_LIST_ADD_ITEM';
export const SURVEY_LIST_ADD_ITEM_SUCCESS = 'SURVEY_LIST_ADD_ITEM_SUCCESS';
export const SURVEY_LIST_ADD_ITEM_ERROR = 'SURVEY_LIST_ADD_ITEM_ERROR';
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE = 'SURVEY_LIST_SELECTED_ITEMS_CHANGE';
export const SURVEY_LIST_DELETE_ITEMS = 'SURVEY_LIST_DELETE_ITEMS';
export const SURVEY_LIST_DELETE_ITEMS_SUCCESS = 'SURVEY_LIST_DELETE_ITEMS_SUCCESS';
export const SURVEY_LIST_DELETE_ITEMS_ERROR = 'SURVEY_LIST_DELETE_ITEMS_ERROR';
export const SURVEY_LIST_COPY_ITEMS = 'SURVEY_LIST_COPY_ITEMS';
export const SURVEY_LIST_COPY_ITEMS_SUCCESS = 'SURVEY_LIST_COPY_ITEMS_SUCCESS';
export const SURVEY_LIST_COPY_ITEMS_ERROR = 'SURVEY_LIST_COPY_ITEMS_ERROR';
export const SURVEY_LIST_SHARE_ITEM = 'SURVEY_LIST_SHARE_ITEM';
export const SURVEY_LIST_SHARE_ITEM_SUCCESS = 'SURVEY_LIST_SHARE_ITEM_SUCCESS';
export const SURVEY_LIST_SHARE_ITEM_ERROR = 'SURVEY_LIST_SHARE_ITEM_ERROR';
export const SURVEY_LIST_ACTIVE_ITEM = 'SURVEY_LIST_ACTIVE_ITEM';
export const SURVEY_LIST_ACTIVE_ITEM_SUCCESS = 'SURVEY_LIST_ACTIVE_ITEM_SUCCESS';
export const SURVEY_LIST_ACTIVE_ITEM_ERROR = 'SURVEY_LIST_ACTIVE_ITEM_ERROR';
export const SURVEY_LIST_SET_MULTI_RESPONSES_ITEM = 'SURVEY_LIST_SET_MULTI_RESPONSES_ITEM';
export const SURVEY_LIST_SET_MULTI_RESPONSES_ITEM_SUCCESS = 'SURVEY_LIST_SET_MULTI_RESPONSES_ITEM_SUCCESS';
export const SURVEY_LIST_SET_MULTI_RESPONSES_ITEM_ERROR = 'SURVEY_LIST_SET_MULTI_RESPONSES_ITEM_ERROR';

/* SHARED SURVEY LIST APP */
export const SHARED_SURVEY_LIST_GET_LIST = 'SHARED_SURVEY_LIST_GET_LIST';
export const SHARED_SURVEY_LIST_GET_LIST_SUCCESS = 'SHARED_SURVEY_LIST_GET_LIST_SUCCESS';
export const SHARED_SURVEY_LIST_GET_LIST_ERROR = 'SHARED_SURVEY_LIST_GET_LIST_ERROR';
export const SHARED_SURVEY_LIST_GET_LIST_WITH_FILTER = 'SHARED_SURVEY_LIST_GET_LIST_WITH_FILTER';
export const SHARED_SURVEY_LIST_GET_LIST_WITH_ORDER = 'SHARED_SURVEY_LIST_GET_LIST_WITH_ORDER';
export const SHARED_SURVEY_LIST_GET_LIST_SEARCH = 'SHARED_SURVEY_LIST_GET_LIST_SEARCH';
export const SHARED_SURVEY_LIST_ADD_ITEM = 'SHARED_SURVEY_LIST_ADD_ITEM';
export const SHARED_SURVEY_LIST_ADD_ITEM_SUCCESS = 'SHARED_SURVEY_LIST_ADD_ITEM_SUCCESS';
export const SHARED_SURVEY_LIST_ADD_ITEM_ERROR = 'SHARED_SURVEY_LIST_ADD_ITEM_ERROR';
export const SHARED_SURVEY_LIST_SELECTED_ITEMS_CHANGE = 'SHARED_SURVEY_LIST_SELECTED_ITEMS_CHANGE';
export const SHARED_SURVEY_LIST_DELETE_ITEMS = 'SHARED_SURVEY_LIST_DELETE_ITEMS';
export const SHARED_SURVEY_LIST_DELETE_ITEMS_SUCCESS = 'SHARED_SURVEY_LIST_DELETE_ITEMS_SUCCESS';
export const SHARED_SURVEY_LIST_DELETE_ITEMS_ERROR = 'SHARED_SURVEY_LIST_DELETE_ITEMS_ERROR';
export const SHARED_SURVEY_LIST_COPY_ITEMS = 'SHARED_SURVEY_LIST_COPY_ITEMS';
export const SHARED_SURVEY_LIST_COPY_ITEMS_SUCCESS = 'SHARED_SURVEY_LIST_COPY_ITEMS_SUCCESS';
export const SHARED_SURVEY_LIST_COPY_ITEMS_ERROR = 'SHARED_SURVEY_LIST_COPY_ITEMS_ERROR';
export const SHARED_SURVEY_LIST_SHARE_ITEM = 'SHARED_SURVEY_LIST_SHARE_ITEM';
export const SHARED_SURVEY_LIST_SHARE_ITEM_SUCCESS = 'SHARED_SURVEY_LIST_SHARE_ITEM_SUCCESS';
export const SHARED_SURVEY_LIST_SHARE_ITEM_ERROR = 'SHARED_SURVEY_LIST_SHARE_ITEM_ERROR';

/* CATEGORY LIST APP */
export const CATEGORY_LIST_GET_LIST = 'CATEGORY_LIST_GET_LIST';
export const CATEGORY_LIST_GET_LIST_SUCCESS = 'CATEGORY_LIST_GET_LIST_SUCCESS';
export const CATEGORY_LIST_GET_LIST_ERROR = 'CATEGORY_LIST_GET_LIST_ERROR';
export const CATEGORY_LIST_ADD_ITEM = 'CATEGORY_LIST_ADD_ITEM';
export const CATEGORY_LIST_ADD_ITEM_SUCCESS = 'CATEGORY_LIST_ADD_ITEM_SUCCESS';
export const CATEGORY_LIST_ADD_ITEM_ERROR = 'CATEGORY_LIST_ADD_ITEM_ERROR';

/* SURVEY */
export const GET_SURVEY = 'GET_SURVEY';
export const GET_SURVEY_SHARE = 'GET_SURVEY_SHARE';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_ERROR = 'GET_SURVEY_ERROR';
export const UPDATE_SURVEY = 'UPDATE_SURVEY';
export const UPDATE_SURVEY_SUCCESS = 'UPDATE_SURVEY_SUCCESS';
export const UPDATE_SURVEY_ERROR = 'UPDATE_SURVEY_ERROR';

/* RESULT LIST */
export const RESULT_LIST_GET_LIST = 'RESULT_LIST_GET_LIST';
export const RESULT_LIST_GET_LIST_SUCCESS = 'RESULT_LIST_GET_LIST_SUCCESS';
export const RESULT_LIST_GET_LIST_ERROR = 'RESULT_LIST_GET_LIST_ERROR';
export const RESULT_LIST_GET_ITEM = 'RESULT_LIST_GET_ITEM';
export const RESULT_LIST_GET_ITEM_SUCCESS = 'RESULT_LIST_GET_ITEM_SUCCESS';
export const RESULT_LIST_GET_ITEM_ERROR = 'RESULT_LIST_GET_ITEM_ERROR';
export const RESULT_LIST_POST_ITEM = 'RESULT_LIST_POST_ITEM';
export const RESULT_LIST_POST_ITEM_SUCCESS = 'RESULT_LIST_POST_ITEM_SUCCESS';
export const RESULT_LIST_POST_ITEM_ERROR = 'RESULT_LIST_POST_ITEM_ERROR';
export const RESULT_LIST_UPDATE_ITEM = 'RESULT_LIST_UPDATE_ITEM';
export const RESULT_LIST_UPDATE_ITEM_SUCCESS = 'RESULT_LIST_UPDATE_ITEM_SUCCESS';
export const RESULT_LIST_UPDATE_ITEM_ERROR = 'RESULT_LIST_UPDATE_ITEM_ERROR';
export const RESULT_LIST_POST_MANUAL_ITEM = 'RESULT_LIST_POST_MANUAL_ITEM';
export const RESULT_LIST_POST_MANUAL_ITEM_SUCCESS = 'RESULT_LIST_POST_MANUAL_ITEM_SUCCESS';
export const RESULT_LIST_POST_MANUAL_ITEM_ERROR = 'RESULT_LIST_POST_MANUAL_ITEM_ERROR';

/* REPORT LIST */
export const REPORT_LIST_GET_LIST = 'REPORT_LIST_GET_LIST';
export const REPORT_LIST_GET_LIST_SUCCESS = 'REPORT_LIST_GET_LIST_SUCCESS';
export const REPORT_LIST_GET_LIST_ERROR = 'REPORT_LIST_GET_LIST_ERROR';
export const REPORT_LIST_GET_ITEM = 'REPORT_LIST_GET_ITEM';
export const REPORT_LIST_GET_ITEM_SUCCESS = 'REPORT_LIST_GET_ITEM_SUCCESS';
export const REPORT_LIST_GET_ITEM_ERROR = 'REPORT_LIST_GET_ITEM_ERROR';
export const REPORT_LIST_GET_ITEM_SHARE = 'REPORT_LIST_GET_ITEM_SHARE';
export const REPORT_LIST_UPDATE_ITEM = 'REPORT_LIST_UPDATE_ITEM';
export const REPORT_LIST_UPDATE_ITEM_SUCCESS = 'REPORT_LIST_UPDATE_ITEM_SUCCESS';
export const REPORT_LIST_UPDATE_ITEM_ERROR = 'REPORT_LIST_UPDATE_ITEM_ERROR';
export const REPORT_LIST_ADD_ITEM = 'REPORT_LIST_ADD_ITEM';
export const REPORT_LIST_ADD_ITEM_SUCCESS = 'REPORT_LIST_ADD_ITEM_SUCCESS';
export const REPORT_LIST_ADD_ITEM_ERROR = 'REPORT_LIST_ADD_ITEM_ERROR';
export const REPORT_LIST_DELETE_ITEM = 'REPORT_LIST_DELETE_ITEM';
export const REPORT_LIST_DELETE_ITEM_SUCCESS = 'REPORT_LIST_DELETE_ITEM_SUCCESS';
export const REPORT_LIST_DELETE_ITEM_ERROR = 'REPORT_LIST_DELETE_ITEM_ERROR';
export const REPORT_LIST_ADD_SECTION = 'REPORT_LIST_ADD_SECTION';
export const REPORT_LIST_UPDATE_SECTION = 'REPORT_LIST_UPDATE_SECTION';
export const REPORT_LIST_RESET_SHARE_LINK = 'REPORT_LIST_RESET_SHARE_LINK';
export const REPORT_LIST_RESET_SHARE_LINK_SUCCESS = 'REPORT_LIST_RESET_SHARE_LINK_SUCCESS';
export const REPORT_LIST_RESET_SHARE_LINK_ERROR = 'REPORT_LIST_RESET_SHARE_LINK_ERROR';
export const REPORT_LIST_CHANGE_SAVING = 'REPORT_LIST_CHANGE_SAVING';

/* USER */
export const USER_LIST_GET_LIST = 'USER_LIST_GET_LIST';
export const USER_LIST_GET_LIST_SUCCESS = 'USER_LIST_GET_LIST_SUCCESS';
export const USER_LIST_GET_LIST_ERROR = 'USER_LIST_GET_LIST_ERROR';
export const USER_LIST_ADD_ITEM = 'USER_LIST_ADD_ITEM';
export const USER_LIST_ADD_ITEM_SUCCESS = 'USER_LIST_ADD_ITEM_SUCCESS';
export const USER_LIST_ADD_ITEM_ERROR = 'USER_LIST_ADD_ITEM_ERROR';
export const USER_LIST_DELETE_ITEMS = 'USER_LIST_DELETE_ITEMS';
export const USER_LIST_DELETE_ITEMS_SUCCESS = 'USER_LIST_DELETE_ITEMS_SUCCESS';
export const USER_LIST_DELETE_ITEMS_ERROR = 'USER_LIST_DELETE_ITEMS_ERROR';
export const USER_LIST_CHANGE_ORGANIZATION = 'USER_LIST_CHANGE_ORGANIZATION';
export const USER_LIST_CHANGE_ORGANIZATION_SUCCESS = 'USER_LIST_CHANGE_ORGANIZATION_SUCCESS';
export const USER_LIST_CHANGE_ORGANIZATION_ERROR = 'USER_LIST_CHANGE_ORGANIZATION_ERROR';

/* PILLAR LIST APP */
export const PILLAR_LIST_GET_LIST = 'PILLAR_LIST_GET_LIST';
export const PILLAR_LIST_GET_LIST_SUCCESS = 'PILLAR_LIST_GET_LIST_SUCCESS';
export const PILLAR_LIST_GET_LIST_ERROR = 'PILLAR_LIST_GET_LIST_ERROR';
export const PILLAR_LIST_ADD_ITEM = 'PILLAR_LIST_ADD_ITEM';
export const PILLAR_LIST_ADD_ITEM_SUCCESS = 'PILLAR_LIST_ADD_ITEM_SUCCESS';
export const PILLAR_LIST_ADD_ITEM_ERROR = 'PILLAR_LIST_ADD_ITEM_ERROR';

/* WEB LINK LIST */
export const WEB_LINK_LIST_GET_LIST = 'WEB_LINK_LIST_GET_LIST';
export const WEB_LINK_LIST_GET_LIST_ERROR = 'WEB_LINK_LIST_GET_LIST_ERROR';
export const WEB_LINK_LIST_GET_LIST_SUCCESS = 'WEB_LINK_LIST_GET_LIST_SUCCESS';
export const WEB_LINK_LIST_ADD_ITEM = 'WEB_LINK_LIST_ADD_ITEM';
export const WEB_LINK_LIST_ADD_ITEM_ERROR = 'WEB_LINK_LIST_ADD_ITEM_ERROR';
export const WEB_LINK_LIST_ADD_ITEM_SUCCESS = 'WEB_LINK_LIST_ADD_ITEM_SUCCESS';
export const WEB_LINK_LIST_UPDATE_ITEM = 'WEB_LINK_LIST_UPDATE_ITEM';
export const WEB_LINK_LIST_UPDATE_ITEM_ERROR = 'WEB_LINK_LIST_UPDATE_ITEM_ERROR';
export const WEB_LINK_LIST_UPDATE_ITEM_SUCCESS = 'WEB_LINK_LIST_UPDATE_ITEM_SUCCESS';
export const WEB_LINK_LIST_DELETE_ITEM = 'WEB_LINK_LIST_DELETE_ITEM';
export const WEB_LINK_LIST_DELETE_ITEM_ERROR = 'WEB_LINK_LIST_DELETE_ITEM_ERROR';
export const WEB_LINK_LIST_DELETE_ITEM_SUCCESS = 'WEB_LINK_LIST_DELETE_ITEM_SUCCESS';

/* EMAIL LINK LIST */
export const EMAIL_LINK_LIST_GET_LIST = 'EMAIL_LINK_LIST_GET_LIST';
export const EMAIL_LINK_LIST_GET_LIST_ERROR = 'EMAIL_LINK_LIST_GET_LIST_ERROR';
export const EMAIL_LINK_LIST_GET_LIST_SUCCESS = 'EMAIL_LINK_LIST_GET_LIST_SUCCESS';
export const EMAIL_LINK_LIST_ADD_ITEM = 'EMAIL_LINK_LIST_ADD_ITEM';
export const EMAIL_LINK_LIST_ADD_ITEM_ERROR = 'EMAIL_LINK_LIST_ADD_ITEM_ERROR';
export const EMAIL_LINK_LIST_ADD_ITEM_SUCCESS = 'EMAIL_LINK_LIST_ADD_ITEM_SUCCESS';
export const EMAIL_LINK_LIST_UPDATE_ITEM = 'EMAIL_LINK_LIST_UPDATE_ITEM';
export const EMAIL_LINK_LIST_UPDATE_ITEM_ERROR = 'EMAIL_LINK_LIST_UPDATE_ITEM_ERROR';
export const EMAIL_LINK_LIST_UPDATE_ITEM_SUCCESS = 'EMAIL_LINK_LIST_UPDATE_ITEM_SUCCESS';
export const EMAIL_LINK_LIST_DELETE_ITEM = 'EMAIL_LINK_LIST_DELETE_ITEM';
export const EMAIL_LINK_LIST_DELETE_ITEM_ERROR = 'EMAIL_LINK_LIST_DELETE_ITEM_ERROR';
export const EMAIL_LINK_LIST_DELETE_ITEM_SUCCESS = 'EMAIL_LINK_LIST_DELETE_ITEM_SUCCESS';
export const EMAIL_LINK_LIST_SEND_EMAIL = 'EMAIL_LINK_LIST_SEND_EMAIL';
export const EMAIL_LINK_LIST_SEND_EMAIL_ERROR = 'EMAIL_LINK_LIST_SEND_EMAIL_ERROR';
export const EMAIL_LINK_LIST_SEND_EMAIL_SUCCESS = 'EMAIL_LINK_LIST_SEND_EMAIL_SUCCESS';

/* ORGANIZATION */
export const ORGANIZATION_LIST_GET_LIST = 'ORGANIZATION_LIST_GET_LIST';
export const ORGANIZATION_LIST_GET_LIST_SUCCESS = 'ORGANIZATION_LIST_GET_LIST_SUCCESS';
export const ORGANIZATION_LIST_GET_LIST_ERROR = 'ORGANIZATION_LIST_GET_LIST_ERROR';
export const ORGANIZATION_LIST_GET_LIST_FILTER = 'ORGANIZATION_LIST_GET_LIST_FILTER';
export const ORGANIZATION_LIST_ADD_ITEM = 'ORGANIZATION_LIST_ADD_ITEM';
export const ORGANIZATION_LIST_ADD_ITEM_SUCCESS = 'ORGANIZATION_LIST_ADD_ITEM_SUCCESS';
export const ORGANIZATION_LIST_ADD_ITEM_ERROR = 'ORGANIZATION_LIST_ADD_ITEM_ERROR';
export const ORGANIZATION_LIST_DELETE_ITEMS = 'ORGANIZATION_LIST_DELETE_ITEMS';
export const ORGANIZATION_LIST_DELETE_ITEMS_SUCCESS = 'ORGANIZATION_LIST_DELETE_ITEMS_SUCCESS';
export const ORGANIZATION_LIST_DELETE_ITEMS_ERROR = 'ORGANIZATION_LIST_DELETE_ITEMS_ERROR';

/* DASHBOARD */
export const DASHBOARD_GET_MY_INFO = 'DASHBOARD_GET_MY_INFO';
export const DASHBOARD_GET_MY_INFO_SUCCESS = 'DASHBOARD_GET_MY_INFO_SUCCESS';
export const DASHBOARD_GET_MY_INFO_ERROR = 'DASHBOARD_GET_MY_INFO_MY_INFO';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
export * from './surveyList/actions';
export * from './sharedSurvey/actions';
export * from './categoryList/actions';
export * from './survey/actions';
export * from './result/actions';
export * from './report/actions';
export * from './weblink/actions';
export * from './emaillink/actions';
export * from './user/actions';
export * from './organization/actions';
export * from './pillar/actions';
export * from './dashboard/actions';
